implement authentication
kalviumcommunity/AgroShield pull request #4
Opened 2023-03-09 05:40 UTC by anmolsingh0001

implement authentication

2023-03-10 10:57 UTC, aditya-190 requested changes
Pls make the required changes before merging.

2023-03-10 10:57 UTC, aditya-190 commented on backend/server.js
> +        },'n8tv3222hk')
Please add this private key inside your .env file and use from there.

2023-03-10 10:57 UTC, aditya-190 commented on frontend/src/Components/Navbar.js
> +        (inputvalu)?
rename this variable to `inputValue`

2023-03-13 07:05 UTC, PatelNeelMahesh approved these changes
You can merge pull request.

2023-03-13 07:06 UTC, merged